version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    container_name: front
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env